version: '3'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    networks:
       - app-tier
    volumes:
       - .DB/mysql/db:/var/lib/mysql
    ports:
       - "3306:3306"
    cap_add:
       - SYS_NICE
    environment:
       - MYSQL_DATABASE=app
       - MYSQL_USER=user
       - MYSQL_PASSWORD=1234
       - MYSQL_ROOT_PASSWORD=1234

  flask_app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
       - "5000:5000"
    links:
       - mysql_db:mysql_db
    depends_on:
       - mysql_db
    networks:
       - app-tier
    restart: always
    volumes:
       - ./backend/app:/app
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app
    
  react-native:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
       - 8081:8081
    volumes:
       - ./frontend:/node
    networks:
       - app-tier

networks:
    app-tier:
      driver: bridge
